# Basic dependabot.yml file with
# minimum configuration for maven package manager

version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
